=== Thomah/Alize/build/classes/reseaux.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="Reseau" type="Reseau">
		
	</xsd:element>
	
	<xsd:complexType name="Reference">
		<xsd:attribute name="ref" type="Identifiant" />
	</xsd:complexType>
	
	<xsd:simpleType name="Identifiant">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-9]*" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="Reseau">
		<xsd:sequence>
			<xsd:element name="intervalles">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Intervalle" type="Intervalle" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="arrets">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Arret" type="Arret" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="depots">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Depot" type="Reference" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="lignes">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Ligne" type="Ligne" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="transitions">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Transition" type="Transition" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Intervalle">
		<xsd:choice minOccurs="1" maxOccurs="3">
			<xsd:element name="min" type="xsd:time"/>
			<xsd:element name="pref" type="xsd:time"/>
			<xsd:element name="max" type="xsd:time"/>
		</xsd:choice>
		<xsd:attribute name="id" type="Identifiant" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="Arret">
		<xsd:attribute name="id" type="Identifiant" use="required" />
		<xsd:attribute name="nom" type="xsd:string" use="required" />
		<xsd:attribute name="estCommercial" type="xsd:boolean" use="optional" default="true" />
		<xsd:attribute name="estEntreeSortieDepot" type="xsd:boolean" use="optional" default="false" />
		<xsd:attribute name="estLieuEchangeConducteur" type="xsd:boolean" use="optional" default="false" />
		<xsd:attribute name="tempsImmobilisation" type="Identifiant" use="required" />
	</xsd:complexType>
	
	<xsd:complexType name="Ligne">
		<xsd:sequence>
			<xsd:element name="voies">
				<xsd:complexType>
					<xsd:sequence minOccurs="1" maxOccurs="unbounded">
						<xsd:element name="Voie" type="Voie" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="Identifiant" use="required"/>
	</xsd:complexType>
	
	<xsd:complexType name="Voie">
		<xsd:sequence>
			<xsd:element name="arrets">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Arret" type="Reference" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="terminusDepart">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Terminus" type="Reference" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="terminusArrivee">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="Terminus" type="Reference" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="direction" />
	</xsd:complexType>
	
	<xsd:complexType name="Transition">
		<xsd:sequence>
			<xsd:element name="arretPrecedent">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Arret" type="Reference"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="arretSuivant">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="Arret" type="Reference"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="id" type="Identifiant" use="required"/>
		<xsd:attribute name="duree" type="xsd:time" use="required"/>
	</xsd:complexType>
	
</xsd:schema>

=== Thomah/Alize/nau/src/main/resources/reseaux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<Reseau xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="reseaux.xsd">

	<intervalles>
		<Intervalle id="immo-arret-foch-maison-bleue">
			<pref>00:01:00</pref>
		</Intervalle>
		<Intervalle id="immo-depot-1">
			<min>00:30:00</min>
			<pref>10:00:00</pref>
		</Intervalle>
		<Intervalle id="immo-term-A-1">
			<min>00:10:00</min>
			<pref>00:15:00</pref>
			<max>00:45:00</max>
		</Intervalle>
	</intervalles>

	<lignes>
		<Ligne id="A">

			<depots>
				<Depot tempsImmobilisation="immo-depot-1" />
			</depots>

			<voies>
				<Voie direction="Avrillé">
					<arrets>
						<Arret id="foch-haras" nom="Foch Haras" estCommercial="true"
							estEntreeSortieDepot="false" tempsImmobilisation="immo-arret-a-foch-maison-bleue"
							estLieuEchangeConducteur="true" />
						<Arret id="foch-maison-bleue" nom="Foch Maison Bleue"
							estCommercial="true" estEntreeSortieDepot="false"
							tempsImmobilisation="immo-arret-a-foch-maison-bleue"
							estLieuEchangeConducteur="true" />
					</arrets>
					<terminus>
						<Terminus id="angers-roseraie" nom="Angers Roseraie"
							estCommercial="true" estEntreeSortieDepot="false"
							tempsImmobilisation="immo-term-A-1" estLieuEchangeConducteur="true" />
						<Terminus id="avrille-ardenne" nom="Avrillé Ardenne"
							estCommercial="true" estEntreeSortieDepot="false"
							tempsImmobilisation="immo-term-A-1" estLieuEchangeConducteur="true" />
					</terminus>
				</Voie>
			</voies>

		</Ligne>
	</lignes>

	<transitions>
		<Transition id="trans-angers-roseraie-foch-haras" duree="00:20:00">
			<arretPrecedent>
				<Arret ref="angers-roseraie" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="foch-haras" />
			</arretSuivant>
		</Transition>
		<Transition id="trans-foch-haras-foch-maison-bleue" duree="00:01:00">
			<arretPrecedent>
				<Arret ref="foch-haras" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="foch-maison-bleue" />
			</arretSuivant>
		</Transition>
		<Transition id="trans-foch-maison-bleue-avrille-ardenne"
			duree="00:25:00">
			<arretPrecedent>
				<Arret ref="foch-maison-bleue" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="avrille-ardenne" />
			</arretSuivant>
		</Transition>
	</transitions>

</Reseau>

=== Thomah/Alize/src/main/resources/reseaux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<Reseau xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="reseaux.xsd">

	<intervalles>
		<Intervalle id="immo-arret-foch-maison-bleue">
			<pref>00:01:00</pref>
		</Intervalle>
		<Intervalle id="immo-depot-1">
			<min>00:30:00</min>
			<pref>10:00:00</pref>
		</Intervalle>
		<Intervalle id="immo-term-A-1">
			<min>00:10:00</min>
			<pref>00:15:00</pref>
			<max>00:45:00</max>
		</Intervalle>
	</intervalles>

	<arrets>
		<Arret id="foch-haras" nom="Foch Haras" estCommercial="true"
			estEntreeSortieDepot="false" tempsImmobilisation="immo-arret-a-foch-maison-bleue"
			estLieuEchangeConducteur="true" />
		<Arret id="foch-maison-bleue" nom="Foch Maison Bleue"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="immo-arret-a-foch-maison-bleue"
			estLieuEchangeConducteur="true" />
		<Arret id="angers-roseraie" nom="Angers Roseraie"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="immo-term-A-1" estLieuEchangeConducteur="true" />
		<Arret id="avrille-ardenne" nom="Avrillé Ardenne"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="immo-term-A-1" estLieuEchangeConducteur="true" />
		<Arret id="ctt" nom="CTT"
			estCommercial="false" estEntreeSortieDepot="false"
			tempsImmobilisation="immo-depot-1" estLieuEchangeConducteur="true" />
	</arrets>
	
	<depots>
		<Depot ref="ctt" />
	</depots>
	
	<lignes>
		<Ligne id="A">

			<voies>
				<Voie direction="Avrillé">
					<arrets>
						<Arret ref="foch-haras" />
						<Arret ref="foch-maison-bleue" />
					</arrets>
					<terminusDepart>
						<Terminus ref="angers-roseraie" />
					</terminusDepart>
					<terminusArrivee>
						<Terminus ref="avrille-ardenne" />
					</terminusArrivee>
				</Voie>
			</voies>

		</Ligne>
	</lignes>

	<transitions>
		<Transition id="trans-angers-roseraie-foch-haras" duree="00:20:00">
			<arretPrecedent>
				<Arret ref="angers-roseraie" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="foch-haras" />
			</arretSuivant>
		</Transition>
		<Transition id="trans-foch-haras-foch-maison-bleue" duree="00:01:00">
			<arretPrecedent>
				<Arret ref="foch-haras" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="foch-maison-bleue" />
			</arretSuivant>
		</Transition>
		<Transition id="trans-foch-maison-bleue-avrille-ardenne"
			duree="00:25:00">
			<arretPrecedent>
				<Arret ref="foch-maison-bleue" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="avrille-ardenne" />
			</arretSuivant>
		</Transition>
	</transitions>

</Reseau>

=== Thomah/Alize/src/test/resources/reseaux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xml>

<Reseau xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="reseaux.xsd">

	<intervalles>
		<Intervalle id="1">
			<pref>00:01:00</pref>
		</Intervalle>
		<Intervalle id="2">
			<min>00:30:00</min>
			<pref>10:00:00</pref>
		</Intervalle>
		<Intervalle id="3">
			<min>00:10:00</min>
			<pref>00:15:00</pref>
			<max>00:45:00</max>
		</Intervalle>
	</intervalles>

	<arrets>
		<Arret id="1" nom="Foch Haras" estCommercial="true"
			estEntreeSortieDepot="false" tempsImmobilisation="1"
			estLieuEchangeConducteur="true" />
		<Arret id="2" nom="Foch Maison Bleue"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="1"
			estLieuEchangeConducteur="true" />
		<Arret id="3" nom="Angers Roseraie"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="3" estLieuEchangeConducteur="true" />
		<Arret id="4" nom="Avrillé Ardenne"
			estCommercial="true" estEntreeSortieDepot="false"
			tempsImmobilisation="3" estLieuEchangeConducteur="true" />
		<Arret id="5" nom="CTT"
			estCommercial="false" estEntreeSortieDepot="false"
			tempsImmobilisation="2" estLieuEchangeConducteur="true" />
	</arrets>
	
	<depots>
		<Depot ref="5" />
	</depots>
	
	<lignes>
		<Ligne id="1">

			<voies>
				<Voie direction="Avrillé">
					<arrets>
						<Arret ref="1" />
						<Arret ref="2" />
					</arrets>
					<terminusDepart>
						<Terminus ref="3" />
					</terminusDepart>
					<terminusArrivee>
						<Terminus ref="4" />
					</terminusArrivee>
				</Voie>
			</voies>

		</Ligne>
	</lignes>

	<transitions>
		<Transition id="1" duree="00:20:00">
			<arretPrecedent>
				<Arret ref="3" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="1" />
			</arretSuivant>
		</Transition>
		<Transition id="2" duree="00:01:00">
			<arretPrecedent>
				<Arret ref="1" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="2" />
			</arretSuivant>
		</Transition>
		<Transition id="3"
			duree="00:25:00">
			<arretPrecedent>
				<Arret ref="2" />
			</arretPrecedent>
			<arretSuivant>
				<Arret ref="4" />
			</arretSuivant>
		</Transition>
	</transitions>

</Reseau>
